# streamlit_app.py
# Streamlit UI that talks to the Modal web endpoints.
# - Dropdown to pick a plan (oldest -> latest, default latest)
# - Shows per-stock live P&L and total gain/loss
import os
from typing import Dict, Any, List, Optional

import requests
import pandas as pd
import streamlit as st

# ------------------------------------------------
# Config – set these ENV VARs in Streamlit Cloud
# ------------------------------------------------
MODAL_LIST_PLANS_URL = os.getenv(
    "MODAL_LIST_PLANS_URL",
    "https://inmemory-latest-infer--list_plans.modal.run",  # replace with your URL
)
MODAL_GET_PLAN_URL = os.getenv(
    "MODAL_GET_PLAN_URL",
    "https://inmemory-latest-infer--get_plan_with_live.modal.run",  # replace with your URL
)

# ------------------------------------------------
# Helpers to talk to Modal (cached)
# ------------------------------------------------
@st.cache_data(ttl=60)
def fetch_plan_list() -> List[Dict[str, Any]]:
    resp = requests.get(MODAL_LIST_PLANS_URL, timeout=60)
    resp.raise_for_status()
    data = resp.json()
    return data.get("plans", [])

@st.cache_data(ttl=30)
def fetch_plan_with_live(plan_id: Optional[str]) -> Dict[str, Any]:
    params: Dict[str, str] = {}
    if plan_id:
        params["id"] = plan_id
    resp = requests.get(MODAL_GET_PLAN_URL, params=params, timeout=120)
    resp.raise_for_status()
    return resp.json()

# ------------------------------------------------
# UI
# ------------------------------------------------
st.set_page_config(page_title="InterFusion Investment Plans", layout="wide")
st.title("Investment Plans (InterFusion Bi-Encoder)")
st.caption("Plans are generated by Modal at 9am Melbourne time. "
           "Buy prices & quantities are recorded at creation; live prices are fetched on demand.")

# 1) Load plans; if none, trigger creation via Modal
plans = fetch_plan_list()
if not plans:
    st.warning("No plans yet. Creating the first plan on Modal...")
    _ = fetch_plan_with_live(plan_id=None)
    fetch_plan_list.clear()
    plans = fetch_plan_list()

if not plans:
    st.error("Still no plans available after attempting creation. Check your Modal app logs.")
    st.stop()

# 2) Dropdown (oldest -> latest, default latest)
labels = [p["label"] for p in plans]
ids = [p["plan_id"] for p in plans]
default_index = len(labels) - 1
selected_label = st.selectbox("Select investment plan", labels, index=default_index)
selected_id = ids[labels.index(selected_label)]

# 3) Fetch selected plan with live prices & PnL
data = fetch_plan_with_live(selected_id)
if "error" in data:
    st.error(f"Error from Modal: {data['error']}")
    st.stop()

plan = data["plan"]
rows = data.get("rows", [])
total_cost = data.get("total_cost", 0.0)
total_value = data.get("total_value", 0.0)
total_pnl = data.get("total_pnl", 0.0)
total_pnl_pct = data.get("total_pnl_pct", 0.0)

st.subheader(f"Plan for date {plan['date']}")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Plan invest amount", f"${plan['invest_amt']:,.2f}")
c2.metric("Top-k stocks", int(plan["k"]))
c3.metric("Current total value", f"${total_value:,.2f}")
c4.metric("Total P&L", f"${total_pnl:,.2f}", f"{total_pnl_pct:.2f}%")

st.markdown("---")

if not rows:
    st.warning("No rows in this plan.")
else:
    df = pd.DataFrame(rows)
    # Format columns for display
    def fmt_money(x):
        return "—" if pd.isna(x) else f"${x:,.2f}"
    def fmt_num(x):
        return "—" if pd.isna(x) else f"{x:,.4f}"

    df_display = df.copy()
    df_display["allocation_$"]   = df_display["allocation"].map(fmt_money)
    df_display["buy_price"]      = df_display["buy_price"].map(fmt_money)
    df_display["quantity"]       = df_display["quantity"].map(fmt_num)
    df_display["live_price"]     = df_display["live_price"].map(fmt_money)
    df_display["position_value"] = df_display["position_value"].map(fmt_money)
    df_display["pnl_$"]          = df_display["pnl"].map(fmt_money)
    df_display["pnl_%"]          = df_display["pnl_pct"].map(lambda x: "—" if pd.isna(x) else f"{x:.2f}%")

    cols = ["rank","ticker","item_id","allocation_$","buy_price","quantity","live_price","position_value","pnl_$","pnl_%","score","weight"]
    cols = [c for c in cols if c in df_display.columns]
    st.dataframe(df_display[cols], use_container_width=True, hide_index=True)

st.markdown("---")
st.caption("Not financial advice. Powered by Modal (compute) + Streamlit (UI).")
